
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


mail.remitente=valdes.l.juanfrancisco@gmail.com
mail.clave=xobf hiby hpir wbwl
mail.host=smtp.gmail.com
mail.port=587